version: "3.8"

services:
  app:
      build: .
      ports:
          - 3000:3000
          
  selenium-hub:
  image: selenium/hub:latest
  ports:
    - "4444:4444"

chrome-node:
  image: selenium/node-chrome:latest
  depends_on:
    - selenium-hub