version: "3.8"

services:
  app:
      build: .
      ports:
          - 3000:3000

  jenkins:
    image: myjenkins-blueocean:2.414.3-1
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    restart: always
          
  # selenium-hub:
  # image: selenium/hub:latest
  # ports:
  #   - "4444:4444"

  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git

# chrome-node:
#   image: selenium/node-chrome:latest
#   depends_on:
#     - selenium-hub

